### ISSUE TITLE
Upstream into podman

### ISSUE THREAD

**Issue by ibotty** [containers/quadlet#11]
I am very interested in this effort.  It looks like the right idea!

I could not find any github issue or discussion regarding integration into podman.  It would be great (for me!) to update that issue with links to discussion or integration.

Thanks.

**Comment by rhatdan** [comment]
SGTM

**Comment by ibotty** [comment]
Any updates?  It would be great to have in Fedora CoreOS and it being included in podman would make that easier.

**Comment by jdoss** [comment]
I second @ibotty having this included with Podman or build generator support into Podman itself and Pod support for group would really make life easier on FCOS.

**Comment by M1cha** [comment]
I was integrated already and they even improved it A LOT.
https://github.com/containers/podman/pulls?q=is%3Apr+quadlet+is%3Aclosed

**Comment by ibotty** [comment]
Great!
