### ISSUE TITLE
Multiple containers? (pods)

### ISSUE THREAD

**Issue by xeor** [containers/quadlet#12]
Would it make sense to add support for multiple containers in the same format as well? I would like to replace podman-compose with something like this

**Comment by rhatdan** [comment]
I think this would be a POD. Or do you just want to link namespaces together?

**Comment by alexlarsson** [comment]
I guess you can already do instancing using systemd if you name the file `foo@.container`, which will generate `foo@.service`, which systemd sees as a template. Then you can `systemctl start foo@1.service foo@2.service`.

**Comment by alexlarsson** [comment]
When you say "linked", do you mean having a port from the redis container available in the app container, or do you mean full network namespace sharing, like `--network=container:systemd-redis`.

**Comment by alexlarsson** [comment]
Eh, I meant a slice, not a scope

**Comment by giuseppe** [comment]
> @giuseppe I think we talked about this, right. If i pass --cgroups=split for a container in a pod then podman ignores the cgroup for the pod, right?

yes, `--cgroups=split` is supposed to use the current cgroup

**Comment by trusch** [comment]
Is this something that is still considered? I'd love to see this feature being supported since having pods is kind of a unique selling point for podman in general and having that exposed with a nice API through quadlet would be fantastic.

**Comment by rhatdan** [comment]
We are supporting Pods only via the new kubelet support. See in Podman since quadlet has been merged.
