### ISSUE TITLE
Support for UDP Ports

### ISSUE THREAD

**Issue by b-m-f** [containers/quadlet#18]
Currently is does not seem possible to add the protocol for `PublishPort`.

What should be possible? -> `80:80/udp`

I guess this code https://github.com/containers/quadlet/blob/main/src/generator.c#L519 would need one more switch case?

I have not written any C code before, but if you think this would be a good addition I can give it a try over the weekend :)

**Comment by XenGi** [comment]
Seems like it's just splitting the string up on the `:` so the `/udp` or `/tcp` should stay with the port number. Are you sure it doesn't work? I haven't tested it myself yet.

**Comment by b-m-f** [comment]
@XenGi will recheck this these days!
Maybe I made a mistake somewhere

**Comment by XenGi** [comment]
@b-m-f will do the same in a few minutes cause I need a container with exposed UDP too. :)

**Comment by XenGi** [comment]
So it seems, something isn't working correctly.

I tried this:
```shell
$ podman run -it --rm -u 900 -p 15777:15777/udp -p 15000:15000/udp -p 7777:7777/udp registry.gitlab.com/xengi-containers/satisfactory:latest
```
And got this result:
```shell
$ ss -tulpen | grep 7777
udp   UNCONN 0      0                    0.0.0.0:7777       0.0.0.0:*    ino:15848781 sk:11 cgroup:/ <->
```

Then I created the following container:
```ini
[Unit]
Description=Satisfactory Dedicated Server container

[Container]
Image=registry.gitlab.com/xengi-containers/satisfactory:latest
PublishPort=15777:15777/udp
PublishPort=15000:15000/udp
PublishPort=7777:7777/udp
User=900

[Service]
Restart=always

[Install]
WantedBy=multi-user.target default.target
```
It starts up but it doesn't seem to bind to the UDP ports.

**Comment by XenGi** [comment]
I found the issue. The regex that detects ports and ranges simply needed an addition for detecting the protocol suffix. I also added test cases and created a pull request: https://github.com/containers/quadlet/pull/19

**Comment by b-m-f** [comment]
Thanks @XenGi !

**Comment by XenGi** [comment]
Is this project still alive?

**Comment by rhatdan** [comment]
Yes,  I am not sure what is going on with @alexlarsson

**Comment by XenGi** [comment]
Can someone ping @alexlarsson? I hope he's alright. Last activity on GitHub was just 14 days ago. Maybe someone else from the containers project could step in in the mean time. I mean live and paying work is always more important then open source work. So having multiple maintainers per project makes sense. The bus factor, you know. ;)

**Comment by XenGi** [comment]
Hi @alexlarsson, good to see you. Thx for merging. I'll try to implement something for my other issue when I find time.
