### ISSUE TITLE
[Feature Request] Ability to change/disable "systemd-" container prefix

### ISSUE THREAD

**Issue by ryester19** [containers/quadlet#31]
For simple hobby servers that only host a few services, the "systemd-" prefix feels unnecessary and just adds to the typing that needs to be done to administer the containers.

It would be nice if the user could change the "systemd-" container prefix to something else, or even removed completely

**Comment by mattdm** [comment]
> For simple hobby servers that only host a few services, the "systemd-" prefix feels unnecessary and just adds to the typing that needs to be done to administer the containers.

Or actually conversely: systems where _all_ of the containers are managed by systemd via quadlet, where it's just then redundant.

**Comment by alexlarsson** [comment]
I'd like by default to have the `systemd-` prefix to avoid accidentally stomping on the users namespace. However, having a key like `ContainerNamePrefix=` or something to override that sounds fine to me.

**Comment by alexlarsson** [comment]
Actually maybe not a prefix option, but  a `ContainerName=` option. That seems both clearer and more flexible.
