### ISSUE TITLE
--pull=never is problematic if container storage is empty

### ISSUE THREAD

**Issue by ibotty** [containers/quadlet#37]
When container storage is empty, on system start no containers managed by quadlet can actually run.  That might happen on clean installs or when an admin replaces the container storage.  What's the best way to address that problem?

**Comment by rhatdan** [comment]
--pull missing works with Podman.

**Comment by ibotty** [comment]
Should quadlet use `--pull missing` instead?  I'd certainly prefer it doing so.

**Comment by rhatdan** [comment]
Since quadlet has been merged into podman, we are sticking to the contianers.conf defaults.  Certain distributions might want to default to pull=missing in their containers.conf, and then quadlet will use those defaults, but so will podman run.
